---

- name: Install packages
  hosts: tag_Group_Elasticsearch:tag_Group_Kibana:tag_Group_Logstash
  become: true
  tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - nmap

- name: Determine nodes to join in Prod
  hosts: tag_Group_Elasticsearch
  become: true
  tasks:
  - name: Setting nodes IPs 
    set_fact:
      join_list: "{{ groups['tag_Environment_Production'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename 

- name: Determine nodes to join in NonProd
  hosts: tag_Group_Elasticsearch
  become: true
  tasks:
  - name: Setting nodes IPs 
    set_fact:
      NonProd_list: "{{ groups['tag_Environment_NonProd'] | map('extract', hostvars, ['ansible_host']) | list | default(5) }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
    when: tag_Environment_NonProd is defined
    #when: ('tag_Environment_NonProd' in group_names) 

- name: Register variables based on tags
  hosts: tag_Group_Elasticsearch
  become: true
  tasks:
  - name: Cluster name variable 
    set_fact:
      cluster_name: "{{ ec2_tag_ClusterName }}"
    when: "'ec2' in group_names"

- name: Elasticsearch srv01 set up
  hosts: tag_Group_Elasticsearch
  roles:
    - role: elastic.elasticsearch
      when: ('tag_Environment_Production' in group_names)
  vars:
    es_heap_size: "512m"
    es_config:
      network.host: 0.0.0.0
      cluster.name: "{{ cluster_name }}"
      cluster.initial_master_nodes: "{{ join_list | join(',') }}"
      discovery.seed_hosts: "{{ join_list | join(',') }}"
      http.port: 9200
      node.master: true
      bootstrap.memory_lock: false
    es_api_port: 9200
    es_plugins:
     - plugin: ingest-attachment
  

- name: Elasticsearch non-prod set up
  hosts: tag_Group_Elasticsearch
  roles:
    - role: elastic.elasticsearch
      when: ('tag_Environment_NonProd' in group_names)
  vars:
    es_heap_size: "512m"
    es_config:
      network.host: 0.0.0.0
      cluster.name: "{{ cluster_name }}"
      cluster.initial_master_nodes: "{{ NonProd_list | join(',') }}"
      discovery.seed_hosts: "{{ NonProd_list | join(',') }}"
      http.port: 9201
      node.master: true
      bootstrap.memory_lock: false
    es_api_port: 9201
    es_plugins:
     - plugin: ingest-attachment
  

- name: Notification
  hosts: tag_Group_Elasticsearch
  tasks:
    - debug:
        msg: "Elasticsearch job finished successfully!"
                                                                                                                                                                             

