---
- name: Install packages
  hosts: tag_Group_Elasticsearch:tag_Group_Kibana:tag_Group_Logstash
  become: true
  tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - nmap

          #- name: Edit host file on all hosts
          #  hosts: all
          #  gather_facts: False
          #  tasks:
          #  - name: update hosts file
          #    become: true
          #    blockinfile:
          #      dest: /etc/hosts
          #      content: "{{ lookup('template', '/etc/ansible/templates/hosts.j2') }}"
          #      state: present

- name: Determine nodes to join
  set_fact:
    join_list: "{{ groups['tag_Group_Elasticsearch'] | map('extract', hostvars, ['ansible_host']) | list }}"

- name: Elasticsearch srv01 set up
  hosts: tag_Group_Elasticsearch
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "512m"
    es_config:
#      node.name: ip-10-174-21-11.tattsgroup.io
      network.host: 0.0.0.0
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "{{ groups.tag_Group_Elasticsearch | map('extract', hostvars, 'ec2_private_ip_address') | list }}"
      discovery.seed_hosts: "{{ join_list | join(',') }}"
      http.port: 9200
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

# - name: Elasticsearch srv02 set up
#   hosts: 10.174.21.64
#   roles:
#     - role: elastic.elasticsearch
#   vars:
#     es_heap_size: "512m"
#     es_data_dirs:
#       - "/opt/elasticsearch"
#     es_config:
#       node.name: ip-10-174-21-64.tattsgroup.io
#       network.host: 0.0.0.0
#       cluster.name: "test-cluster"
#       cluster.initial_master_nodes: "ip-10-174-21-11.tattsgroup.io,ip-10-174-21-64.tattsgroup.io,ip-10-174-21-195.tattsgroup.io"
#       discovery.seed_hosts: "ip-10-174-21-11.tattsgroup.io,ip-10-174-21-64.tattsgroup.io,ip-10-174-21-195.tattsgroup.io"
#       http.port: 9200
#       node.master: true
#       bootstrap.memory_lock: false
#     es_plugins:
#       - plugin: ingest-attachment

# - name: Elasticsearch srv03 set up
#   hosts: 10.174.21.195
#   roles:
#     - role: elastic.elasticsearch
#   vars:
#     es_heap_size: "512m"
#     es_config:
#       node.name: ip-10-174-21-195.tattsgroup.io
#       network.host: 0.0.0.0
#       cluster.name: "test-cluster"
#       cluster.initial_master_nodes: "ip-10-174-21-11.tattsgroup.io,ip-10-174-21-64.tattsgroup.io,ip-10-174-21-195.tattsgroup.io"
#       discovery.seed_hosts: "ip-10-174-21-11.tattsgroup.io,ip-10-174-21-64.tattsgroup.io,ip-10-174-21-195.tattsgroup.io"
#       http.port: 9200
#       node.master: true
#       bootstrap.memory_lock: false
#     es_plugins:
#       - plugin: ingest-attachment

- name: Notification
  hosts: tag_Group_Elasticsearch
  tasks:
    - debug:
        msg: "Elasticsearch job finished successfully!"
                                                                                                                                                                             

