---
- name: Install packages
  hosts: tag_Group_Elasticsearch:tag_Group_Kibana:tag_Group_Logstash
  become: true
  tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - nmap

- name: Determine nodes to join
  hosts: tag_Group_Elasticsearch
  become: true
  tasks:
  - name: Setting nodes IPs 
    set_fact:
      join_list: "{{ groups['tag_Group_Elasticsearch'] | map('extract', hostvars, ['ansible_host']) | list }}"

- name: Elasticsearch srv01 set up
  hosts: tag_Group_Elasticsearch
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "512m"
    es_config:
#      node.name: ip-10-174-21-11.tattsgroup.io
      network.host: 0.0.0.0
      cluster.name: "test-cluster"
      cluster.initial_master_nodes: "{{ groups.tag_Group_Elasticsearch | map('extract', hostvars, ['ansible_host']) | list }}"
      discovery.seed_hosts: 10.174.21.11,10.174.21.64,10.174.21.195
      http.port: 9200
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- name: Notification
  hosts: tag_Group_Elasticsearch
  tasks:
    - debug:
        msg: "Elasticsearch job finished successfully!"
                                                                                                                                                                             

