---
- name: Install packages
  hosts: Logstash-Group
  become: true
  tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - nmap
        - java-1.8.0-openjdk

- name: Logstash setup
  hosts: Logstash-Group
  roles: 
    - geerlingguy.logstash
  vars: 
    logstash_elasticsearch_hosts:
      - http://10.174.21.11:9200
      - http://10.174.21.64:9200
      - http://10.174.21.195:9200
    logstash_local_syslog_path: /var/log/messages 

- name: Notification
    debug:
      msg: "Logstash job finished successfully!"
