---

#Install packages - all enviroments

- name: Install packages
  hosts: tag_Group_Logstash:tag_Environment_Test
  become: true
  tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - nmap
        - java-1.8.0-openjdk

# Test environment configuration

- name: Setting up production Logstash
  hosts: tag_Environment_Test
  become: true
  tags: # Tag which is used in Jenkins file to skip this job
  - test
  tasks:
  - name: Setting nodes IP list # Creating variable Test_list which is the list of all elasticsearch hosts
    set_fact:
      Test_list: "{{ groups['tag_Environment_Test'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
  - name: Debug Test_list # Debugging the list - making sure that the list is correct
    debug:
       msg: "{{ Test_list }}"
  - name: Modify nodes IP list # Creating variable TestElasticsearchList which is the same as Test_list but with appended prefix http and suffix 9200
    vars:
      TestElasticsearchList: [] 
    set_fact:
       TestElasticsearchList: "{{ Test_list | map('regex_replace', '(.*)', 'http://\\1:9200') | list }}"
  - name: Debug  # Debugging the list - making sure that the list is correct
    debug:
       msg: "{{ TestElasticsearchList }}"

  - name: Test Logstash setup # Logstash configuration
    import_role: 
      name: geerlingguy.logstash
    when: ('tag_Environment_Test' in group_names)
    vars: 
      logstash_elasticsearch_hosts: "{{ TestElasticsearchList }}"      
      logstash_local_syslog_path: /var/log/messages 

# Production environment configuration

- name: Setting up production Logstash
  hosts: tag_LogstashProd_Group
  become: true
  tags: # Tag which is used in Jenkins file to skip this job
  - prod
  tasks:
  - name: Setting nodes IP list 
    set_fact:
      Prod_list: "{{ groups['tag_ElasticsearchProd_Group'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
  - name: Debug # Debugging the list - making sure that the list is correct
    debug:
       msg: "{{ Prod_list }}"
  - name: Modify nodes IP list # Creating variable ProdElasticsearchList which is the same as Prod_list but with appended prefix http and suffix 9210
    vars:
      ProdElasticsearchList: [] 
    set_fact:
       ProdElasticsearchList: "{{ Prod_list | map('regex_replace', '(.*)', 'http://\\1:9200') | list }}"
  - name: Debug  # Debugging the list - making sure that the list is correct
    debug:
       msg: "{{ ProdElasticsearchList }}"

  - name: Prod Logstash setup # Logstash configuration
    import_role: 
      name: geerlingguy.logstash
    when: ('tag_Environment_Production' in group_names)
    vars: 
      logstash_elasticsearch_hosts: "{{ ProdElasticsearchList }}"      
      logstash_local_syslog_path: /var/log/messages 

- name: Notification # Notification
  hosts: tag_Group_Logstash
  tasks:
    - debug:
        msg: "Logstash job finished successfully!!!"
