---

- hosts: all
  tasks:
    - name: Insert a line at the end of a file.
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAqWo/B7KD6qMr+QZsPjUeX2jvU459yY8YGM/g5LSw9erZLTEdy81ekGUs3EEw4zKTvltoVD+eXCscBWyjCjezIHMjHd9YBthbWurB1Bzq79ygVRVFyPnxyIJJVCPh3kG2BOcJ4BtfJUr4EixYiEE58yl6jsgsD47L9NWuA5raiguZijjpXe6bWwunDinvKJknrrSfxVJa62CU+qE0fS2AlsyKuFs3IjHOLb7x82bZG01NHa2Xkrt1YHnZimSEMwEia86Uutodu4p81t/8FfHQmzw+4nwlB4TxnHtJpkl20hbFlTkWEAhWEySkgAJPLz4q9k/zKFVMsOS7kIjlFLuv root@awx"
