---
- name: hosts file 
  hosts: all
  gather_facts: yes
  tasks:
    - debug: var=hostvars[groups['app'][0]].ansible_host
    - name: Update /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{item}}$'
        line: "{{ 'hostvars[item]['ansible_default_ipv4']['address']' }} {{item}}"
        state: present
      register: etchostsupdate
      when: hostvars[item]['ansible_facts']['default_ipv4'] is defined
      with_items:
        - "{{ groups['all'] }}"