---
- name: Create nginx container
  hosts: ip-10-174-21-221.tattsgroup.io
  become: true
  tasks:
    - name: Install packages
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - htop
          - python2-pip
          - docker

    - name: PIP Install
      pip:
        name: docker
    
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy nginx conf
      copy:
        src: /etc/ansible/files/nginx.conf
        dest: /root/nginx.conf
        mode: '755'

    - name: Create nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        volumes:
          - /root/nginx.conf:/etc/nginx/nginx.conf:rw
        published_ports:
          - "80:80"
