---

# Install packages

- name: Install packages
  hosts: tag_Group_Grafana
  become: true
  tasks:
    - name: Install packages
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - htop
          - python2-pip
          - docker
    - name: PIP install Docker
      pip:
        name: docker

- name: Setting up test Grafana
  hosts: tag_Group_Grafana
  become: true
  tags: # Tag which is used in Jenkins file to skip this job
  - test
  tasks:
  - name: Grafana production role # Grafana configuration
    import_role: 
      name: ansible-grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: "{{ admin_password }}"
      grafana_datasources:
        - name: elasticsearch
          type: elasticsearch
          access: server
          database: "metricbeat-7.5.2"
          url: 'http://localhost:9200'
          basicAuth: false
          tlsAuth: false
          tlsAuthWithCACert: false
          tlsSkipVerify: false
          readOnly: false
          editable: true
          jsonData:
            timeField: "@timestamp"
            esVersion: 70
            maxConcurrentShardRequests: 5
      grafana_dashboards:
        - dashboard_id: 11567
          revision_id: 1
          datasource: elasticsearch


  post_tasks:
  - name: Notification
    debug:
      msg: "Test Grafana job finished successfully!"
