---

# Install packages

- name: Install packages
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
    - name: Install packages
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - htop
          - python2-pip
          - docker
    - name: PIP install Docker
      pip:
        name: docker

# Start and enable Docker

- name: Start and enable Docker service
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
  - name: Services
    service:
      name: docker
      state: started
      enabled: yes

# Copy Nginx conf file

- name: Nginx
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
  - name: Nginx file
    copy:
      src: /etc/ansible/files/nginx.conf
      dest: /root/nginx.conf

# Create Nginx container

- name: Create nginx container
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
  - name: Create container
    docker_container:
      name: nginx
      image: nginx:latest
      volumes:
        - /root/nginx.conf:/etc/nginx/nginx.conf:rw
      published_ports:
        - "80:80"

# TEST environment configuration

- name: Setting up test Kibana
  hosts: tag_Environment_Test
  become: true
  tags: # Tag which is used in Jenkins file to skip this job
  - test
  tasks:
  - name: Setting nodes IP list # Creating variable Test_list which is the list of all elasticsearch hosts
    set_fact:
      Test_list: "{{ groups['tag_Environment_Test'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
  - name: Debug Test_list # Debugging the list - making sure that the list is correct
    debug:
       msg: "{{ Test_list }}"
  - name: Modify nodes IP list # Creating variable TestKibanaList which is the same as Test_list but with appended prefix http and suffix 9200
    vars:
      TestKibanaList: []
    set_fact:
       TestKibanaList: "{{ Test_list | map('regex_replace', '(.*)', 'http://\\1:9200') | list }}"
  - name: Debug TestKibanaList # Debugging the list - making sure that the list is correct 
    debug:
       msg: "{{ TestKibanaList }}"

  - name: Kibana test role # Kibana configuration
    import_role:
      name: geerlingguy.kibana
    when: ('tag_Environment_Test' in group_names)
    vars:
      kibana_version: 7.x
      kibana_config_template: "/etc/ansible/templates/kibana.j2"
      kibana_elasticsearch_url: "{{ TestKibanaList }}"
      kibana_elasticsearch_hosts: "{{ TestKibanaList }}"

# Production environment configuration

- name: Setting up production Kibana
  hosts: tag_KibanaProd_Group
  become: true
  tags: # Tag which is used in Jenkins file to skip this job
  - prod
  tasks:
  - name: Setting nodes IP list # Creating variable Prod_list which is the list of all elasticsearch hosts
    set_fact:
      Prod_list: "{{ groups['tag_ElasticsearchProd_Group'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
  - name: Debug Prod_list # Debugging the list - making sure that the list is correct 
    debug:
       msg: "{{ Prod_list }}"
  - name: Modify nodes IP list # Creating variable ProdKibanaList which is the same as Prod_list but with appended prefix http and suffix 9200
    vars:
      ProdKibanaList: [] 
    set_fact:
       ProdKibanaList: "{{ Prod_list | map('regex_replace', '(.*)', 'http://\\1:9200') | list }}"
  - name: Debug ProdKibanaList # Debugging the list - making sure that the list is correct 
    debug:
       msg: "{{ ProdKibanaList }}"

  - name: Kibana production role # Kibana configuration
    import_role:
      name: geerlingguy.kibana
    when: ('tag_KibanaProd_Group' in group_names)
    vars:
      kibana_version: 7.x
      kibana_config_template: "/etc/ansible/templates/kibana.j2"
      kibana_elasticsearch_url: "{{ ProdKibanaList }}"
      kibana_elasticsearch_hosts: "{{ ProdKibanaList }}"

# Notification

# - name: Notification
#   hosts: tag_Environment_Test
#   become: true
#   tasks:
#   - name: Notification
#     debug:
#       msg: "Kibana job finished successfully!"

post_tasks:
  - name: Notification
    hosts: tag_Environment_Test
    become: true
    tasks:
    - name: Notification
      debug:
        msg: "Kibana job finished successfully!"


      
