---

# Setting up packages and NGINX container#

- name: Install packages
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
    - name: Install packages
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - htop
          - python2-pip
          - docker
    - name: PIP install Docker
      pip:
        name: docker
    
- name: Start and enable Docker service
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
  - name: Services
    service:
      name: docker
      state: started
      enabled: yes

- name: Nginx
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
  - name: Nginx file
    copy:
      src: /etc/ansible/files/nginx.conf
      dest: /root/nginx.conf

- name: Create nginx container
  hosts: tag_KibanaTest_Group:tag_KibanaProd_Group
  become: true
  tasks:
  - name: Create container
    docker_container:
      name: nginx
      image: nginx:latest
      volumes:
        - /root/nginx.conf:/etc/nginx/nginx.conf:rw
      published_ports:
        - "80:80"

# TEST environment configuration

- name: Setting up test Kibana
  hosts: tag_Environment_Test
  become: true
  tags:
  - test
  tasks:
  - name: Setting nodes IP list 
    set_fact:
      Test_list: "{{ groups['tag_Environment_Test'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
  - name: Debug 
    debug:
       msg: "{{ Test_list }}"
  - name: Modify nodes IP list
    vars:
      TestKibanaList: []
    set_fact:
       TestKibanaList: "{{ Test_list | map('regex_replace', '(.*)', 'http://\\1:9201') | list }}"
  - name: Debug 
    debug:
       msg: "{{ TestKibanaList }}"

  - name: Kibana test role
    import_role:
      name: geerlingguy.kibana
    when: ('tag_Environment_Test' in group_names)
    vars:
      kibana_version: 7.x
      kibana_config_template: "/etc/ansible/templates/kibana.j2"
      kibana_elasticsearch_url: "{{ TestKibanaList }}"
      kibana_elasticsearch_hosts: "{{ TestKibanaList }}"

# Production environment configuration

- name: Setting up production Kibana
  hosts: tag_KibanaProd_Group
  become: true
  tags:
  - prod
  tasks:
  - name: Setting nodes IP list
    set_fact:
      Prod_list: "{{ groups['tag_ElasticsearchProd_Group'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
  - name: Debug 
    debug:
       msg: "{{ Prod_list }}"
  - name: Modify nodes IP list
    vars:
      ProdKibanaList: [] 
    set_fact:
       ProdKibanaList: "{{ Prod_list | map('regex_replace', '(.*)', 'http://\\1:9201') | list }}"
  - name: Debug 
    debug:
       msg: "{{ ProdKibanaList }}"

  - name: Kibana production role
    import_role:
      name: geerlingguy.kibana
    when: ('tag_KibanaProd_Group' in group_names)
    vars:
      kibana_version: 7.x
      kibana_config_template: "/etc/ansible/templates/kibana.j2"
      kibana_elasticsearch_url: "{{ ProdKibanaList }}"
      kibana_elasticsearch_hosts: "{{ ProdKibanaList }}"

# Notification

- name: Notification
  hosts: tag_Environment_Test
  become: true
  tasks:
  - name: Notification
    debug:
      msg: "Kibana job finished successfully!"



# - name: Determine Kibana nodes to join in Prod
#   hosts: tag_KibanaProd_Group
#   become: true
#   tags:
#   - prod
#   tasks:
#   - name: Setting nodes IPs 
#     set_fact:
#       Prod_list: "{{ groups['tag_KibanaProd_Group'] | map('extract', hostvars, ['ansible_host']) | list }}" # instead 'ansible_host' you can use the folloving variables as well: ansible_fqdn, ec2_private_ip_address or ansible_nodename
#   - name: Debug 
#     debug:
#        msg: "{{ Prod_list }}"

# - name: Prod Kibana list
#   hosts: tag_KibanaProd_Group
#   become: true
#   vars:
#     ProdKibanaList: []
#   tasks:
#   - name: Create Kibana servers list 
#     set_fact:
#        ProdKibanaList: "{{ Prod_list | map('regex_replace', '(.*)', 'https://\\1:8000') | list }}"
#   - name: Debug 
#     debug:
#        msg: "{{ ProdKibanaList }}"

# - name: Kibana_prod_set_up
#   hosts: tag_KibanaProd_Group
#   roles:
#   - role: geerlingguy.kibana
#     when: ('tag_KibanaProd_Group' in group_names)
#   vars:
#     kibana_version: 7.x
#     kibana_config_template: "/etc/ansible/templates/kibana.j2"
#     kibana_elasticsearch_url: "{{ ProdKibanaList }}"
#     kibana_elasticsearch_hosts: "{{ ProdKibanaList }}"
      
